- name: Install nginx
  package: { name: nginx, state: present }

- name: Configure nginx site
  copy:
    dest: /etc/nginx/conf.d/app.conf
    content: |
      server {
        listen {{ listen_port }};
        location / {
          proxy_pass http://127.0.0.1:{{ app_port }};
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
        }
      }
- name: Enable & restart nginx
  systemd: { name: nginx, enabled: yes, state: restarted }
